introduction/README.md

This Branch adds the translated Introduction text, from the old gitbook to the new one,
You can test this with npm install and start. Navigate to localhost:4000 to see the new gitbook with this text.

Add Introduction Text (german) to new gitbook

---

basics/architektur/diagramm.md
basics/architektur/komponenten/README.md

This branch adds the reusable texts from the old "Frontend" Section to the new docu.
Just npm install and npm start to see the new gitbook with this texts.

Add old Frontend texts to new Organisation

---

SUMMARY.md
introduction/getting-started/sending-emails.md

This PR adds two links to the SUMMARY from Gitbook, so the getting started documentation is shown correctly. Also one video link is fixed.

🎨 Fix & add linked files

---

README.md

Fix typo in motivation

---

basics/architektur/komponenten/README.md

Fixed a few typos in `basics/architektur/komponenten/README.md`

💄 Fix typos in basics

---

andere-themen/stack/advanced-concepts/configuration.md
andere-themen/stack/module-interaction/README.md
andere-themen/stack/module-interaction/dependendy-injection.md
andere-themen/stack/module-interaction/discovery.md
andere-themen/stack/structure/README.md
anhang/GLOSSARY.md
basics/architektur/komponenten/README.md
bpmn/styleguide.md
introduction/getting-started/hello-bpmn-world.md
introduction/getting-started/http-rest-api.md
introduction/getting-started/sending-emails.md

I added some terms to the glossary and linked them in the documentation, as wished in #24.

📝 Add terms to glossary

---

LICENSE
package.json

:page_facing_up: Add MIT License

---

SUMMARY.md
basics/README.md
bpmn-studio/hands-on/README.md
integration/consumer-client-API/README.md
introduction/getting-started/README.md

This PR updates the navigation and the description/introduction of some topics to not show just empty pages at the most of the headlines.
Checkout the branch and start it with `npm start`.

💄 :lipstick: Update the navigation and topic description

---

SUMMARY.md
andere-themen/stack/advanced-concepts/README.md
andere-themen/stack/basic-concepts/datastore.md
andere-themen/stack/structure/adapters.md
andere-themen/stack/structure/bridges.md
andere-themen/stack/structure/contracts.md
andere-themen/stack/structure/extensions.md

Ich habe den übersetzten Stack in die Navbar bzw. Inhaltsverzeichnis aufgenommen und zusätzlich wichtige Links aktualisiert.

✨ :sparkles: Add stack to navbar and stylefixes

---

Jenkinsfile
ci-tools/checkLinks.sh
ci-tools/parseAndPrepareLinks.js

Adds CI Tooling to detect dead links.

👷 :construction_worker: Add CI Tools to Detect Dead Links

---

andere-themen/stack/advanced-concepts/README.md

💄 :lipstick: Add WIP information

---

.gitignore

This PR adds the package-lock.json to the .gitignore.

✨:sparkles: Add package-lock to gitignore

---

build_prod.sh

This PR fixes the build_prod script.
Closes #70 
- checkout develop
- npm run build-prod

🐛 :bug: Fix build_prod

---

Jenkinsfile
build_prod.sh

Dropped develop as release branch; use master as release branch.

:lipstick: Change Release branch to be master

---

README.md

Fix some typos and remove a duplicated passage.

Fix errors in main readme

---

bpmn-standard/styleguide.md

Deleted contents of grocery list. 
The reader understands the concept of grocery lists, so there is no gain in giving him some examples of what could be in them. The lists are the most prominent thing in the description and each time I read them I'm misleaded into thinking they would play a role later on.
https://github.com/process-engine/documentation/blob/8ea1b195dc2d8933f9ccabc7378882d6fe10f7a7/bpmn-standard/styleguide.md

Remove contents from grocery list

---

README.md

Add a missing comma.
Closes #103.
- Read
- Jenkins will assert that the link is ok.

📝 :memo: Add Missing Comma to README.md

---

book.json
package.json

- Add a link in the top left to edit the page on github
- Checkout
- npm install
- npm start
- Open GitBook
- See the link

✨ :sparkles: Add Improve This Page Link

---

.gitignore

This PR adds the `.vscode` directory to the `.gitignore` file. 

🙈 Add vscode configuration directory to gitignore

---

bpmn-studio/components/diff-view/diff-view.md

This PR updates the Diff View Component Section

📝 Update Diff View

---

bpmn-standard/bpmn-process-engine/terminate-end-event.md

Update description of state and the final code sample to conform to the new process engine.
Read it.

:books: Update TerminateEndEvent Documentation

---

bpmn-studio/components/solution-explorer/solution-explorer.md

Adds a hint that shows all valid characters for the diagram creation
https://github.com/process-engine/bpmn-studio/pull/816#discussion_r211501930

📝 Add Valid Characters for Diagram Creation

---

bpmn-studio/user-guide/basic-editing/basic-editing.md
package.json

**Changes:**
1. Add Some Spacing
2. Add Documentation for PreferredControl for User Tasks
3. Fix Name in Package.json
PR: #132
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of …

📝 Add Confirm Dialog

---

getting-started/examples/hello-bpmn-world.md

**Changes:**
1. Adds link to diagram
**Issues:**
Closes #90 
PR: #PullRequest
---
- `gitbook serve`
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand …

✨ Add link to diagram

---

getting-started/installation.md

**Changes:**
1. Link to the latest release of BPMN Studio
**Issues:**
PR: #152 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …

:memo: Link to Latest Release of BPMN Studio

---

api/consumer_api/tasks/finish-user-task.md
api/consumer_api/tasks/get-correlation-result.md
api/consumer_api/tasks/list-startable-process-models.md
api/consumer_api/tasks/list-triggerable-events.md
api/consumer_api/tasks/list-waiting-usertasks.md
api/consumer_api/tasks/start-process-instance.md
api/consumer_api/tasks/trigger-event.md
api/consumer_api/technical-specifications.md
processengine/typescript/consumer_api/README.md
processengine/typescript/consumer_api/public_api.md
processengine/typescript/consumer_api/tasks/finish-user-task.md
processengine/typescript/consumer_api/tasks/get-correlation-result.md
processengine/typescript/consumer_api/tasks/list-startable-process-models.md
processengine/typescript/consumer_api/tasks/list-waiting-usertasks.md
processengine/typescript/consumer_api/tasks/start-process-instance.md

**Changes:**
This will replace all occurences of `IConsumerApiService` to `IConsumerApi`, so that it properly reflects the current architecture we employ for this API.
PR: #155
Read the docs.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR
</code> …

♻️ Rename occurences of IConsumerApiService to IConsumerApi

---

bpmn-standard/styleguide.md
getting-started/examples/hello-bpmn-world.md
getting-started/examples/http-rest-api.md
getting-started/examples/sending-emails.md
processengine/typescript/architektur/dependendy-injection.md
processengine/typescript/architektur/discovery.md
processengine/typescript/architektur/structure.md
processengine/typescript/konzepte/configuration.md

Gitbook automatically adds links to the glossary. Adding links manually is error prone (number of `../` for depth of file structure and link has to match exactly with entry in glossary). It also leaves the impression that adding links would be necessary.
---
**Changes:**
1. Deletes glossary links
**Issues:**
PR: #149
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this pull …

🔥 Delete glossary links

---

api/consumer_api/dealing_with_events.md
api/consumer_api/tasks/finish-user-task.md
api/consumer_api/tasks/get-correlation-result.md
api/consumer_api/tasks/getting-started.md
api/consumer_api/tasks/list-triggerable-events.md
api/consumer_api/tasks/trigger-event.md

Previously there were 3 way to inline arguments in routes.
Now just one (prepending :).
---
**Changes:**
1. Uses the same syntax for inlining arguments everywhere
**Issues:**
None
PR: #146
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …

🐛 Apply one syntax to documentation of routes

---

GLOSSARY.md

**Changes:**
1. Add Token description to glossar.
**Issues:**
#123 is related, but not entirely done with this.
PR: #148
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …

📝 Feature/add token to glossary

---

SUMMARY.md

SendEmail example is not reproducible with current bpmn-studio, because right now servicetasks can only be httpservice or externaltask services.
This example can easily be reintroduced at some point.
---
**Changes:**
1. Unlink not working example
**Issues:**
Related to https://github.com/process-engine/bpmn-studio/issues/1083
PR: #160
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: …

🔥 Unlink sendemail example

---

02_getting_started/examples/README.md
SUMMARY.md

---
SendMail works again and can therefore be included again.
This makes https://github.com/process-engine/documentation/pull/162 obsolete(that feature removes a link to the example).
**Changes:**
1. Adds example again
1. Adds the wording change from the now obsolete branch(so that I can delete it)
**Issues:**
None
PR: #164
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong …

📝 Reintroduce SendMail

---

02_getting_started/examples/hello-bpmn-world.md
02_getting_started/examples/http-rest-api.md
02_getting_started/examples/sending-emails.md

Applies changes from the example repository to documentation.
**Changes:**
1. Adds motivation to examples (_why do I learn this_)
1. Adds learning targets to examples (_what do I learn here_)
1. This includes the following examples:
- hello world
- rest api
- send mail
**Issues:**
#163 
PR: #165
Related PRs:
- https://github.com/process-engine/example_processes/pull/26
- https://github.com/process-engine/example_processes/pull/25
- https://github.com/process-engine/example_processes/pull/24
---
1. Clone repository
1. `npm i`
1. `gitbook serve`
<details>
<summary>
</summary>
<br>
Please use …

📝 Add motivation to examples

---

03_bpmn-studio/components/design-view/design-view.md

Wrong indentation caused the markdown table to not be rendered as a table.
EDIT: Check https://www.process-engine.io/documentation/03_bpmn-studio/components/design-view/design-view.html
Before:
---
**Changes:**
1.  Remove table with icon explanations.
2. Replace table by simple explanations of the icons. 
PR: #170
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text …

🐛 Fix Markdown Rendering of Table

---

build_prod.sh

We changed the deployment and hosting of the documentation.
This PR contains the adjustments to the script for automated build and deploy.
**Changes:**
1. Change the script for deployment
2. Use docs folder
PR: #172
---
1. `bash -x build_prod.sh`
1. `cd docs`
1. Start a web server of your choice:
`python -m SimpleHTTPServer`
1. Navigate to the site.

:sparkles: Update the Script for New Deployment

---

01_introduction/motivation.md
02_getting_started/README.md
03_bpmn-studio/components/solution-explorer/solution-explorer.md
04_guidelines/deploy/deploy.md
04_guidelines/start/start.md
07_apis_of_consumer_domain/02_external_task_api/tasks/fetch-and-lock.md
think-design-inspect/README.md

I went through the documentation and caught some typos. 
---
**Changes:**
1. Fixes typos
1. Improves wording at some places
**Issues:**
None
PR: #174
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary> …

💄 📖 Fix typos
